require(xlsx)
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FDATA.gov_NGAP.xlsx", destfile="./data/ngap.xlsx", method="curl")
dfx <- read.xlsx("./data/ngap.xlsx", sheetIndex=1, header=TRUE)
dat <- read.xlsx("./data/ngap.xlsx", rowIndex=18:23, colIndex=7:15, sheetIndex=1, header=TRUE)
sum(dat$Zip*dat$Ext,na.rm=T) 
